#sudo: false
sudo: required
dist: trusty

language: python

python:
    - "3.4"

virtualenv:
  system_site_packages: true

install:
  - pip install -r requirements.txt
  - pip install codecov
  # Alternative: setup.py install.
  # Using pip makes sure that the package is pip-compatible, too.
  - pip install .

# run tests
script:
  - nosetests --with-coverage --cover-package=launchpadtools

after_success:
  - codecov
